version: '3.8'

services:
  web:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    image: web:dev
    ports:
      - '3000:3000'
    restart: always
    environment:
      - NODE_ENV=development
  backend:
    image: ghcr.io/in2siders/backend:latest
    ports:
      - '5000:5000'
    restart: always
    volumes:
      - backend-data:/data
    environment:
      - NODE_ENV=production
volumes:
  backend-data: {}